### ISSUE TITLE
Possible relative path error?

### ISSUE THREAD

**Issue by karaipsum** [kartoffels123/ffxiv-tex-converter#2]
Hello,

I noted the output folder may repeat the path of the input folder when I use dds-to-tex, when the input folder is not located in the same folder as the converter.

For example, input folder `D:\GitHub\Mod\Export\DDS` will generate `D:\GitHub\Mod\Export\DDS_tex\GitHub\Mod\Export\DDS`.

I'm relative new with programming and python. Below is a suggestion from ChatGPT to edit the script in `ffxiv_tex_converter.py` from 
`out_path = Path.joinpath(out_folder, Path(
    *path.parts[1:]).with_suffix('.tex'))`
to
`out_path = out_folder / path.relative_to(folder).with_suffix('.tex')`

And then it solved the error in my case.

ChatGPT also made a drag-and-go batch script for me if you're interested.

```bat
@echo off
set current_dir=%~dp0

:: Get folder directory
set folder=%1

if not exist "%folder%" (
    echo Invalid folder: %folder%
    pause
    exit /b
)

cd /d "%current_dir%"

python ffxiv_tex_converter.py -d "%folder%" -c dds-to-tex -p --chunk-size 200

echo Conversion completed.
pause
```

And again, thank you very much for creating this invaluble conversion tool! My mods couldn't have been made without it.

**Comment by kartoffels123** [comment]
The program is only designed to be run in the current working directory where the converter lives. If you give it an absolute path outside the current working directory it will still assume that it's starting from the current working directory (cwd). 

Just make sure your data is in the cwd and write the relative path. Usually the relative path is just a single folder. 

python ffxiv_tex_converter.py -d DDS -c dds-to-tex

Which will give you

DDS_tex/*

You can modify and fork this program as you wish to add the support for your custom pathing. 

Happy modding, 

Kartoffels
